### ISSUE TITLE
dancing types, e.g. Walz, Swing, 

### ISSUE THREAD

**Issue by alexplusde** [jordipons/musicnn#1]
I'd be curious if you can predict the type(s) of dance(s) like Walz, Chacha, Samba, Salsa, West Coast Swing etc.

While there are big music database information avialiable, e.g. whether it's techno, pop, classic, jazz, etc., there are barely information about the type of dance.

I have access to some hundreds of meta information about songs and their dance to start with: https://www.welcher-tanz.de/interpreten/

But I don't know much about python or aggregating waveforms for training. If you want to extend the tags for these information, please feel free to contact me.

**Comment by jordipons** [comment]
It shouldn't be difficult to be done, because all the tools are in place:
1. A dataset for training the models to predict the type(s) of dance(s): http://anasynth.ircam.fr/home/media/ExtendedBallroom
2. The code to train musicnn models: https://github.com/jordipons/musicnn-training

One just needs to train musicnn with the dataset above.
